name: petpaws
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
# waves flutter
  wave: ^0.0.8
# phone internacinal
  international_phone_input: ^1.0.4
#bottom sheet
  modal_bottom_sheet: ^0.2.0+1
#bropdownbutton
  dropdown_search: ^0.4.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  cupertino_icons: ^0.1.3
  
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  awesome_dialog: ^1.2.0
  firebase_storage: ^4.0.0
  image_picker: ^0.6.7+7
  date_format: ^1.0.8
  intl: ^0.16.1
  multiple_select: ^0.1.23
  table_calendar: ^2.2.3
  url_launcher: ^5.6.0
  expansion_tile_card: ^1.1.0
  call_number: ^0.0.1
  badges: ^1.1.3  
  #--slimy-card
  slimy_card: ^1.0.4
  #expansion card
  expansion_card: ^0.1.0
  #toast notification
  fluttertoast: ^7.1.1
  flutter_facebook_login: ^3.0.0
  fancy_bottom_navigation: ^0.3.2  
  google_sign_in: ^4.5.6
  flutter_signin_button: ^1.1.0
  #google maps
  google_maps_flutter: ^1.0.3
  geolocator: ^6.0.0+4
  map_launcher: ^0.12.2
  google_fonts: ^1.1.1
  geocoder: ^0.2.1
  progress_dialog: ^1.2.4
  #cloud functions
  firebase_messaging: ^7.0.3
  cloud_functions: ^0.7.0
  assets_audio_player: ^2.0.13
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  splashscreen:
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/iphone.mp3
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
      - family: Chilanka
        fonts:
          - asset: assets/fonts/Chilanka-Regular.ttf
      - family: Donuts
        fonts:
          - asset: assets/fonts/PWYummyDonuts.ttf
      - family: McLaren
        fonts:
          - asset: assets/fonts/McLaren-Regular.ttf
      - family: Pumpkin-Soup
        fonts:
          - asset: assets/fonts/Pumpkin-Soup.ttf
          - asset: assets/fonts/Pumpkin-Soup-Italic.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages